hook.Add( "PS2_ItemEditOptions", "PS2_ItemEditOptions_Expiry", function( menu, itemClass )
	print( "Hook Called" )
	local btn = menu:AddOption( "Expiration Options", function( )
		local frame = vgui.Create( "DExpiryMenu" )
		frame:MakePopup( )
		frame:Center( )
		frame:SetItemClass( itemClass )
		function frame.OnSave( )
			local expirationTable = frame:GetExpirationTable( )
			ExpiryView:getInstance( ):saveExpiryInfo( itemClass.className, expirationTable )
		end
	end )
	btn:SetImage( "pointshop2/clock125.png" )
	btn.m_Image:SetSize( 16, 16 )
end )